language: python
cache: pip

python:
    - 2.7

install:
    - pip install -r requirements.txt

script:
    - python manage.py test

after_success:
    - pip install codecov
    - pip install codacy-coverage
    - codecov -e DJANGO
    - python-codacy-coverage -r coverage.xml
