# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='image_url',
        ),
    ]
