# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180325_1654'),
        ('blog', '0002_remove_link_image_url'),
    ]

    operations = [
    ]
