# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180114_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('FEAT', 'feature'), ('LINK', 'link')], default='FEAT', max_length=4),
        ),
    ]
