# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180302_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='feature',
            name='author',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='id',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='title',
        ),
        migrations.AddField(
            model_name='feature',
            name='post_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post'),
            preserve_default=False,
        ),
    ]
