# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0008_auto_20180302_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='posttag',
            name='Video',
        ),
        migrations.RemoveField(
            model_name='posttag',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='posttag',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
