# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180303_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default=1, max_length=280),
            preserve_default=False,
        ),
    ]
