# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180303_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='link',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='feature',
            name='image_url',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='image_url',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
